<div class="wrapper style1">

    <div class="container">
        <div class="row">
            <div class="12u skel-cell-important" id="content">
                <article id="main" class="special">
                    <header>
                        <h2><a href="#">Om Odense Muay Thai</a></h2>
                    </header>
                    <section>
                    <p>Klubben har eksisteret siden 1984, det har igennem alle årene været vigtigt at lave gode rammer for en sund træning.&nbsp;Der ligges vægt på at teknikkerne udføres korrekt samtidig med at folk også har det godt og føler sig tilpas.</p>
                    <p>Hos os kan man træne på det niveau man ønsker, om man har lyst til at komme i form eller træne med henblik på kamp bestemmer man selv.<br>
                    Alt udstyr kan købes i klubben til favorable priser.</p>
                    <p>Klubbens lokaler kan lejes til diverse arrangementer om lørdagen, såsom privat holdtræning eller lign.</p>
                    <p>Der vil blive stillet en træner til rådighed fra klubben samt mulighed for at låne klubbens udstyr. Kontakt klubben for nærmere aftale</p>
<strong>Odense Muay Thai Gym</strong><br>
<strong>Rugårdsvej 23</strong><br>
<strong>5000 Odense C<br>
CVR.:&nbsp;30623819</strong></p>
<p><strong>Klubben er åben<br>
</strong><strong>Mandag til torsdag 17-20<br>
</strong><strong></strong><strong>Lørdag 11-13<br>
Søndag 10-12</strong></p>
<p>Kontakt os gerne på klubbens mail: dmthai@hotmail.com</p>

<p><a title="Odense Muay Thai på Facebook" href="https://www.facebook.com/groups/7746707237/" target="_blank"><strong>Besøg Odense Muay Thai på Facebook</strong>
                    <p>&nbsp;</p>
                    <p><strong>Generelt</strong><br>
                    Hvis der skulle være spørgsmål vdr. kontingent eller problemer med betaling, så er det klubbens kasserer Thomas du skal snakke med.&nbsp;Thomas kan træffes i klubben eller på klubbens mail: dmthai@hotmail.com</p>
                    <p><strong><br>
                    Hvis man ikke kan deltage i træningen længere<br>
                    </strong>Hvis man flytter eller af andre grunde ikke ønsker at træne i Odense Muay Thai Gym længere, skal man udfylde en udmeldelses-blanket og aflevere den til en instruktør i klubben.<br>
                    Udmeldelsen er kun gyldig hvis den er udfyldt korrekt og afleveret til en instruktør. Af administrative grunde kan man ikke melde sig ud ved at sende en udmeldelse til klubbens mail.<br>
                    Vi indberetter vores hold-oplysninger til PBS/NETS senest d.15. i hver mdr., så udmeldelsen skal være afleveret før den dag.<br>
                    Efter udmeldelsen er afleveret, skal man selv slette PBS-aftalen i ens netbank, det er ude af vores hænder. Hvis man ikke kan huske hvor man gør det, kan ens kontaktperson i banken altid let hjælpe med det.</p>
                    <p><strong>Kontaktperson vdr. stævner<br>
                    </strong>Nikolaj Weile træffes via klubbens mail dmthai@hotmail.com eller tirsdag//torsdag fra 17-19 i klubben</p>
                    <p>&nbsp;</p>
                    <p><strong>Om forbundet Danish Muay Thai Federation</strong></p>
                    <p>Odense Muay Thai Gym er medlem af <strong>Danish Muay Thai Federation</strong>, officiel hjemmeside <a href="http://nakmuay.com/" target="_blank">http://nakmuay.com</a></p>
                    <p><a href="http://nakmuay.com/regler-vedtaegter/" target="_blank">Se hvilke regler der gælder på forbundets hjemmeside,</a></p>
                    <p><a href="http://nakmuay.com/kategori/klubber/" target="_blank">Her er også en liste over klubber der er medlem af forbundet</a>
                    </section>
            </div>
        </div>
        <!--
        <hr />
        <div class="row">
            <article class="4u special">
                <a href="http://mdomaradzki.deviantart.com/art/Bueller-VII-351975126" class="image featured"><img src="images/pic07.jpg" alt="" /></a>
                <header>
                    <h3><a href="#">Gravida aliquam penatibus</a></h3>
                </header>
                <p>
                    Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                    porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
            </article>
            <article class="4u special">
                <a href="http://mdomaradzki.deviantart.com/art/Home-Bound-Train-II-338912191" class="image featured"><img src="images/pic08.jpg" alt="" /></a>
                <header>
                    <h3><a href="#">Sed quis rhoncus placerat</a></h3>
                </header>
                <p>
                    Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                    porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
            </article>
            <article class="4u special">
                <a href="http://mdomaradzki.deviantart.com/art/Up-is-Down-325005102" class="image featured"><img src="images/pic09.jpg" alt="" /></a>
                <header>
                    <h3><a href="#">Magna laoreet et aliquam</a></h3>
                </header>
                <p>
                    Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                    porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
            </article>
        </div>
        -->
    </div>

</div>