<div class="wrapper style1">

    <div class="container">
        <div class="row">
            <div class="12u skel-cell-important" id="content">
                <article id="main" class="special">
                    <header>
                        <h2><a href="#">Hold og Tider</a></h2>
                    </header>
                    <section>
                        
                    </section>
                    <header>
                        <span class="byline" id="kids">
                            Børnehold
                        </span>
                    </header>
                    <section>
                        <p>
                            <strong>Træningstider:</strong><br />
                            Tirsdag og Torsdag fra 16.30-17.30<br />
                            + Mulighed for teknisk træning fredag 16-17.30<br />
                            + Mulighed for konditionstræning lørdag fra 10-12.00<br />
                            +  Teknisk træning – Søndag - Husk at se FaceBook side fra 10-12.00<br />
                        </p>
                        <p>
                            <strong>Beskrivelse:</strong><br />
                            Dette er børneholdet, der går op til 17års alderen, dette hold sætter specitelt fokus på børnene og deres motorik.<br />
                        </p>
                        <p>
                            Krævet træningsudstyr:</strong><br />
                            T-shirt, Shorts, Boksehandsker, Sjippetov, Sandsækhandsker.<br />
                        </p>
                        <p>
                            <strong>Forudsætninger:</strong><br />
                            Alder under 16år<br />
                        </p>
                    </section>
                    
                    
                    <header>
                        <span class="byline" id="beginner">
                            Begynderhold
                        </span>
                    </header>
                    <section>
                        <p>
                            <strong>Træningstider:</strong><br />
                            Mandag og onsdag fra 17-18.30<br />
                            + Mulighed for teknisk træning om fredagen 16-17.30<br />
                            + Mulighed for konditionstræning lørdag fra 10-12.00<br />
                            + Teknisk træning – Søndag - Husk at se FaceBook side fra 10-12.00<br />
                        </p>
                        <p>
                            <strong>Beskrivelse:</strong><br />
                            På begynderholdet lærer man alle basis teknikkerne og opbygger samtidig 
                            en god grundkondition. Der starter jævnligt nye medlemmer op på dette 
                            hold så der vil altid være nogen på samme niveau at træne med. Der lægges 
                            stor vægt på at teknikker udføres korrekt, såsom slag, spark, grundstilling 
                            og at flytte sig rigtigt.<br />
                            Der trænes primært på puder og sandsække. Klubben stiller sjippetov og 
                            sandsækhandkser til rådighed ved prøvetræning. Træningen foregår af 1½ time.<br />
                        </p>
                        <p>
                            <strong>Krævet træningsudstyr:</strong><br />
                            T-shirt, Shorts, Tandbeskytter, Sjippetov, Sandsækhandsker.<br />
                            Alt udstyr kan lånes i klubben indtil man får sit eget.<br />
                        </p>
                        <p>
                            <strong>Forudsætninger:</strong><br />
                            Ingen, alle er velkomne<br />
                        </p>
                    </section>
                    
                    
                    <header>
                        <span class="byline" id="trained">
                            Øvet og Kamphold
                        </span>
                    </header>
                    <section>
                        <p>
                            <strong>Træningstider:</strong><br />
                            Tirsdag og torsdag 17.30-19.30<br />
                            + Mulighed for teknisk træning fredag 16-17.30<br />
                            + Mulighed for konditionstræning lørdag fra 10-12.00<br />
                            +  Teknisk træning – Søndag - Husk at se FaceBook side fra 10-12.00<br />
                        </p>
                        <p>
                        <strong>Beskrivelse:</strong><br />
                        På dette hold trænes der med henblik på kamp og er derfor målrette de 
                        teknikker den enkelte kæmper skal have trænet før kampen.<br />
                        </p>
                        <p>
                        <strong>Krævet træningsudstyr:</strong><br />
                        T-shirt, Shorts, Tandbeskytter, Hjelm, Boksehandsker, Sjippetov, Sandsækhandsker.<br />
                        </p>
                        <p>
                        <strong>Forudsætninger:</strong><br />
                        Godkendelse af instruktør<br />
                        </p>
                        
                    </section>
                    
                    
                    <header>
                        <span class="byline" id="kickncross">
                            Kick n' Cross
                        </span>
                    </header>
                    <section>
                        <p>
                            <strong>Træningstider:</strong><br />
                            Mandag og Onsdag 18.30-19.30<br />
                            + Mulighed for konditionstræning lørdag fra 10-12.00<br />
                            + Teknisk træning – Søndag - Husk at se FaceBook side fra 10-12.00<br />
                        </p>
                        <p>
                            <strong>Beskrivelse:</strong><br />
                        
                            Sjov og udfordrende træning i 60min hvor man får pulsen op og laver 
                            alt det bedste fra Thaiboksning. Dette indebærer bl.a. slag, spark, 
                            albuer, knæ mv. Selv om fokus ligger på konditionstræning, skader det 
                            ikke at udføre teknikkerne rigtigt. Derfor har vi altid dygtige instruktører 
                            som selv har haft rigtige thaiboksning kampe til at undervise, for at hæve niveauet.<br />
                            + Selv om fokus ikke er på selvforsvar, vil en motionsbokser lære slag, thaiboksning-spark, 
                            albuer og knæ og derfor styrke denne del ligeledes.<br />
                            <br />
                            Der optages løbende nye på dette hold, så man skal ikke være nervøs for om man har 
                            god nok kondition, der tages hele tiden udgangspunt i den enkelte person og folk 
                            kommer med vidt forskellig baggrund.<br />
                        </p>
                        <p>
                            <strong>Krævet træningsudstyr:</strong><br />
                            T-shirt, Shorts, Sjippetov, Sandsækhandsker.<br />
                        <br />
                            Udstyr kan lånes i klubben hvis man ikke har købt sit eget endnu.(eget udstyr vil være og fortrække)<br />
                        </p>
                        <p>
                            <strong>Forudsætninger:</strong><br />
                            Motionsboksning er et selvstændigt hold. Hvis man ønsker at træne både motionsboksning samt 
                            begynder/øvet skal man kontakte kasseren for at få justeret ens kontingent.<br />
                        </p>
                        
                    </section>
                    
                    
                    <header>
                        <h2><a href="#">Anden Information</a></h2>
                        <span class="byline">
                            Fredags Træning
                        </span>
                    </header>
                    <section>
                        <p>
                            <strong>Træningstider:</strong><br />
                            Fredag fra 16-17.30<br />
                            + Denne træning er åben for alle klubbens medlemmer<br />
                        </p>
                        <p>
                            <strong>Beskrivelse:</strong><br />
                        
                            Det primære fokus ligger på at finpudse teknik og øvelser.<br />
                        </p>
                        <p>
                            <strong>Krævet træningsudstyr:</strong><br />
                            T-shirt, Shorts, Tandbeskytter, Hjelm, Boksehandsker, Sjippetov, Sandsækhandsker.<br />
                        <br />
                            Udstyr kan lånes i klubben hvis man ikke har købt sit eget endnu.<br />
                        </p>
                        <p>
                            <strong>Forudsætninger:</strong><br />
                            Ingen, træninge en åben for alle klubbens medlemmer<br />
                        </p>
                        
                    </section>
                    
                    
                    <header>
                        <span class="byline">
                            Konditions træning - Lørdag
                        </span>
                    </header>
                    <section>
                        <p>
                            <strong>Træningstider:</strong><br />
                             Lørdag fra 10-12.00<br />
                            + Denne træning er åben for alle klubbens medlemmer<br />
                        </p>
                        <p>
                            <strong>Beskrivelse:</strong><br />
                        
                            Det primære fokus ligger på at styrke basis-konditionen med sandsæk og diverse 
                            sjove og hårde øvelser. Alle er velkomne, det kræver ikke man har god kondition i forvejen.<br />
                        </p>
                        <p>
                            <strong>Krævet træningsudstyr:</strong><br />
                            T-shirt, Shorts, Sjippetov, Sandsækhandsker.<br />
                        <br />
                            Udstyr kan lånes i klubben hvis man ikke har købt sit eget endnu.<br />
                        </p>
                        <p>
                            <strong>Forudsætninger:</strong><br />
                            Ingen, træninge en åben for alle klubbens medlemmer<br />
                        </p>
                        
                    </section>
                    
                    
                    <header>
                        <span class="byline">
                            Teknisk træning - Søndag<br />
                            <a href="https://www.facebook.com/groups/7746707237/" >Husk at se FaceBook side</a>
                        </span>
                    </header>
                    <section>
                        <p>
                            <strong>Træningstider:</strong><br />
                            Søndag fra 10-12.00<br />
                            + Denne træning er åben for alle klubbens medlemmer<br />
                        </p>
                        <p>
                            <strong>Beskrivelse:</strong><br />
                        
                            Mange medlemmer benytter søndagstræningen til at få trænet teknikker i eget 
                            tempo og med hjælp fra instruktøren. Det er en rigtig god mulighed for at 
                            få finpudset teknikkerne og få gennemarbejdet den tekniske del af Thaiboksning.<br />
                        </p>
                        <p>
                            <strong>Krævet træningsudstyr:</strong><br />
                            T-shirt, Shorts, Sjippetov<br />
                        <br />
                            Udstyr kan lånes i klubben hvis man ikke har købt sit eget endnu.<br />
                        </p>
                        <p>
                            <strong>Forudsætninger:</strong><br />
                            Ingen, træninge en åben for alle klubbens medlemmer<br />
                        </p>
                        
                    </section>
                </article>
            </div>
        </div>
        <!--
        <hr />
        <div class="row">
            <article class="4u special">
                <a href="http://mdomaradzki.deviantart.com/art/Bueller-VII-351975126" class="image featured"><img src="images/pic07.jpg" alt="" /></a>
                <header>
                    <h3><a href="#">Gravida aliquam penatibus</a></h3>
                </header>
                <p>
                    Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                    porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
            </article>
            <article class="4u special">
                <a href="http://mdomaradzki.deviantart.com/art/Home-Bound-Train-II-338912191" class="image featured"><img src="images/pic08.jpg" alt="" /></a>
                <header>
                    <h3><a href="#">Sed quis rhoncus placerat</a></h3>
                </header>
                <p>
                    Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                    porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
            </article>
            <article class="4u special">
                <a href="http://mdomaradzki.deviantart.com/art/Up-is-Down-325005102" class="image featured"><img src="images/pic09.jpg" alt="" /></a>
                <header>
                    <h3><a href="#">Magna laoreet et aliquam</a></h3>
                </header>
                <p>
                    Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                    porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
            </article>
        </div>
        -->
    </div>

</div>