<div class="wrapper style1">

    <div class="container">
        <div class="row">
            <div class="12u skel-cell-important" id="content">
                <article id="main" class="special">
                    <header>
                        <h2><a href="#">Events</a></h2>
                    </header>
                    <section>
                        Hold øje med denne side, her vil alle vore' events komme.
                    </section>
            </div>
        </div>
        <!--
        <hr />
        <div class="row">
            <article class="4u special">
                <a href="http://mdomaradzki.deviantart.com/art/Bueller-VII-351975126" class="image featured"><img src="images/pic07.jpg" alt="" /></a>
                <header>
                    <h3><a href="#">Gravida aliquam penatibus</a></h3>
                </header>
                <p>
                    Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                    porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
            </article>
            <article class="4u special">
                <a href="http://mdomaradzki.deviantart.com/art/Home-Bound-Train-II-338912191" class="image featured"><img src="images/pic08.jpg" alt="" /></a>
                <header>
                    <h3><a href="#">Sed quis rhoncus placerat</a></h3>
                </header>
                <p>
                    Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                    porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
            </article>
            <article class="4u special">
                <a href="http://mdomaradzki.deviantart.com/art/Up-is-Down-325005102" class="image featured"><img src="images/pic09.jpg" alt="" /></a>
                <header>
                    <h3><a href="#">Magna laoreet et aliquam</a></h3>
                </header>
                <p>
                    Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                    porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
            </article>
        </div>
        -->
    </div>

</div>