<!--
The Ryuu Technology License

Copyright 2014 Ryuu Technology by 
KatsuoRyuu <anders-github@drake-development.org>.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
Ryuu Technology shall be visible and readable to anyone using the software 
and shall be written in one of the following ways: Ryuu Technology 
or by using the company logo.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->

<!-- Banner -->
			<div id="banner">
				<h2>Velkommen til <strong>Odense Muay Thai</strong>.</h2>
				<span class="byline">
					Dit sted for Muay Thai, K1 og Kick n' Cross
				</span>
			</div>

		<!-- Carousel -->
			<div class="carousel">
				<div class="reel">

					<article>
						<a href="http://mdomaradzki.deviantart.com/art/Bueller-III-351975087" class="image featured"><img src="/design/omt/images/pic01.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Fed Træning Udendørs</a></h3>
						</header>
						<p>På dyreskue pladsen med OMT, en fed træning med kolonihave hygge og grill.</p>							
					</article>
				
					<article>
						<a href="http://mdomaradzki.deviantart.com/art/Disco-351602759" class="image featured"><img src="/design/omt/images/pic02.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Træning med Abildgaard</a></h3>
						</header>
						<p>Få en gang træning med Abildgaard. Smuk selfie</p>							
					</article>
				
					<article>
						<a href="http://mdomaradzki.deviantart.com/art/The-Patina-of-Time-and-Tide-352128094" class="image featured"><img src="/design/omt/images/pic03.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Midt i sommerheden</a></h3>
						</header>
						<p>Fed træning med en masse svedige mennesker, på en varm summerdag.</p>							
					</article>
				
					<article>
						<a href="http://mdomaradzki.deviantart.com/art/Cityparts-XVIII-350427779" class="image featured"><img src="/design/omt/images/pic04.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Folk på sommerferie?</a></h3>
						</header>
						<p>Intensiv træning med en masse nice' teknikker...</p>							
					</article>
				
					<article>
						<a href="http://mdomaradzki.deviantart.com/art/Vine-Country-381350120" class="image featured"><img src="/design/omt/images/pic05.jpg" alt="" /></a>
						<header>
							<h3><a href="#">Sommerheden og Træning</a></h3>
						</header>
						<p>Endnu et stort sommerhold til træning. Super med så mange i sommerferien</p>							
					</article>

				</div>
			</div>
			
		<!-- Main -->
			<div class="wrapper style2">

				<?= $nextEvent ?>

			</div>

		<!-- Features -->
			<div class="wrapper style1">
				
				<section id="features" class="container special">
					<header>
						<h2>Vi har plads til alle!</h2>
						<span class="byline">Om du har trænet kampsport før, er nybegynder eller måske bare ønsker dig den lækreste krop, så er der et hold for dig!</span>
					</header>
					<div class="row">
						<article class="4u special">
							<a href="http://mdomaradzki.deviantart.com/art/Bueller-VII-351975126" class="image featured"><img src="/design/omt/images/pic07.jpg" alt="" /></a>
							<header>
								<h3><a href="#">Begynder hold</a></h3>
							</header>
							<p>
								På begynderholdet lærer man alle basis teknikkerne og opbygger samtidig en god grundkondition. Der starter jævnligt nye medlemmer op på dette hold så der vil altid være nogen på samme niveau at træne med. Der lægges stor vægt på at teknikker udføres korrekt, såsom slag, spark, grundstilling og at flytte sig rigtigt.
Der trænes primært på puder og sandsække. Klubben stiller sjippetov og sandsækhandkser til rådighed ved prøvetræning. Træningen foregår af 1½ time.
							</p>
						</article>
						<article class="4u special">
							<a href="http://mdomaradzki.deviantart.com/art/Home-Bound-Train-II-338912191" class="image featured"><img src="/design/omt/images/pic08.jpg" alt="" /></a>
							<header>
								<h3><a href="#">Kamphold</a></h3>
							</header>
							<p>
								På dette hold trænes der med henblik på kamp og er derfor målrette de teknikker den enkelte kæmper skal have trænet før kampen.
							</p>
						</article>
						<article class="4u special">
							<a href="http://mdomaradzki.deviantart.com/art/Up-is-Down-325005102" class="image featured"><img src="/design/omt/images/pic09.jpg" alt="" /></a>
							<header>
								<h3><a href="#">Motions hold</a></h3>
							</header>
							<p>
								Sjov og udfordrende træning i 60min hvor man får pulsen op og laver alt det bedste fra Thaiboksning. Dette indebærer bl.a. slag, spark, albuer, knæ mv. Selv om fokus ligger på konditionstræning, skader det ikke at udføre teknikkerne rigtigt. Derfor har vi altid dygtige instruktører som selv har haft rigtige thaiboksning kampe til at undervise, for at hæve niveauet.
+ Selv om fokus ikke er på selvforsvar, vil en motionsbokser lære slag, thaiboksning-spark, albuer og knæ og derfor styrke denne del ligeledes.

Der optages løbende nye på dette hold, så man skal ikke være nervøs for om man har god nok kondition, der tages hele tiden udgangspunt i den enkelte person og folk kommer med vidt forskellig baggrund.
							</p>
						</article>
					</div>
				</section>

			</div>

		
