<!--
The Ryuu Technology License

Copyright 2014 Ryuu Technology by 
KatsuoRyuu <anders-github@drake-development.org>.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
Ryuu Technology shall be visible and readable to anyone using the software 
and shall be written in one of the following ways: Ryuu Technology 
or by using the company logo.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->

<div class="wrapper style1">

    <div class="container">
        <div class="row">
            <div class="12u skel-cell-important" id="content">
                <article id="main" class="special">
                    <header>
                        <h2><a href="#">Gratis prøvetime</a></h2>
                        <span class="byline">
                            Du har altid mulighed for at komme og prøve gratis om det er noget for dig.
                        </span>
                    </header>
                    <center>
                    <img src="/design/omt/images/billede_thai.jpg" alt="" style="width:25%;text-center;"/>
                    </center>
                    <p>
                        Få en gratis prøvetime
                        Hos Odense Muay Thai Gym får alle nye medlemmer én gratis prøvetime. Alle er velkomne, uanset kondition og det eneste du skal medbringe er et par shorts og en t-shirt.

                    </p>
                    <section>
                        <header>
                            <h3>Lån Udstyr de første gange</h3>
                        </header>
                        <p>
                            Klubben råder over alt udstyr som du kan låne indtil du får dit eget udstyr.

                            Træning for nybegyndere foregår mandag/onsdag, hvor du lærer at udføre teknikker korrekt, såsom slag, spark og grundstilling og der trænes primært på puder og sandsække.

                            Odense Muay Thai er og drives som en forening, hvilket for det første betyder, at klubbens medlemmer selv, kan være med til at bestemme nye tiltag og for det andet, at diverse priser er afstemt således, at Danish Muay thai Gym har en sund økonomi, som kommer medlemmerne til gode.
                        </p>
                    </section>
                    <section>
                        <header>
                            <h3>Det er billigt at træne hos Odense Muay Thai:</h3>
                        </header>
                        <p> 
                            <strong>Kamp, øvet -hold:</strong> kun 200,-/mdr. <br />
                            <strong>Begynderholdet:</strong> kun 200,-/mdr. <br />
                            <strong>Kick n' Cross:</strong> kun 150,-/mdr<br />
                            <strong>Motions-thaiboksning + Begynderhold:</strong> 300,- /mdr.<br />

                            Indmeldelse kun: 100kr.<br />

                            Der er ingen bindinger på medlemskab og du bestemmer selv varigheden af dit medlemskab. Du er medlem, indtil du skriftligt melder dig ud, udmeldelse skal ske skriftligt senest 14 dage før næste opkrævning af hensyn til PBS.

                            Odense Muay Thai Gym er en godkendt forening under folkeoplysningsloven og Odense Kommune støtter derfor foreningen.

                            I foreningen er en frivillig bestyrelse som er valgt af medlemmerne, til at føre klubben mod de opsatte mål.
                        </p>
                    </section>
                </article>
            </div>
        </div>
        <!--
        <hr />
        <div class="row">
            <article class="4u special">
                <a href="http://mdomaradzki.deviantart.com/art/Bueller-VII-351975126" class="image featured"><img src="images/pic07.jpg" alt="" /></a>
                <header>
                    <h3><a href="#">Gravida aliquam penatibus</a></h3>
                </header>
                <p>
                    Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                    porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
            </article>
            <article class="4u special">
                <a href="http://mdomaradzki.deviantart.com/art/Home-Bound-Train-II-338912191" class="image featured"><img src="images/pic08.jpg" alt="" /></a>
                <header>
                    <h3><a href="#">Sed quis rhoncus placerat</a></h3>
                </header>
                <p>
                    Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                    porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
            </article>
            <article class="4u special">
                <a href="http://mdomaradzki.deviantart.com/art/Up-is-Down-325005102" class="image featured"><img src="images/pic09.jpg" alt="" /></a>
                <header>
                    <h3><a href="#">Magna laoreet et aliquam</a></h3>
                </header>
                <p>
                    Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
                    porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
                </p>
            </article>
        </div>
        -->
    </div>

</div>