<!DOCTYPE HTML>

<html>
	<head>
		<title>Odense Muay Thai - Fyns bedste Muay Thai Gym</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600" rel="stylesheet" type="text/css" />
		<!--[if lte IE 8]><script src="/design/omt/js/html5shiv.js"></script><![endif]-->
		<script src="/design/omt/js/jquery.min.js"></script>
		<script src="/design/omt/js/jquery.dropotron.min.js"></script>
		<script src="/design/omt/js/skel.min.js"></script>
		<script src="/design/omt/js/skel-panels.min.js"></script>
		<script src="/design/omt/js/init.js"></script>
        <noscript>
			<link rel="stylesheet" href="/design/omt/css/skel-noscript.css" />
			<link rel="stylesheet" href="/design/omt/css/style.css" />
			<link rel="stylesheet" href="/design/omt/css/style-desktop.css" />
			<link rel="stylesheet" href="/design/omt/css/style-noscript.css" />
        </noscript>
		<!--[if lte IE 8]><link rel="stylesheet" href="/design/omt/css/ie8.css" /><![endif]-->
	</head>
	<body class="no-sidebar">

		<!-- Header -->
			<div id="header">
						
				<!-- Inner -->
					<div class="inner">
						<header>
							<h1><a href="#" id="logo"><img src="/design/omt/images/omt.png" /></a></h1>
						</header>
					</div>
				
				<!-- Nav -->
					<nav id="nav">
						<ul>
							<li><a href="/">Forside</a></li>
							<li>
                                <span><a href="/omt/class">Hold</a></span>
								<ul>
									<li><a href="/omt/class#beginner">Begynder</a></li>
									<li><a href="/omt/class#trained">Øvet / Kamp</a></li>
									<li><a href="/omt/class#kids">Børne</a></li>
									<li><a href="/omt/class#kickncross">Motion</a></li>
								</ul>
							</li>
							<li><a href="/omt/tryouts">Gratis Prøvetime</a></li>
							<li><a href="/omt/events">Events</a></li>
							<li><a href="/omt/about">Om</a></li>
						</ul>
					</nav>

			</div>
			
		<?= $content ?>
        <!-- Footer -->
			<div id="footer">
				<div class="container">
                    <!-- for later --
					<div class="row">
						
						<!-- Tweets --
							<section class="4u">
								<header>
									<h2 class="fa fa-facebook circled  solo"><span>Tweets</span></h2>
								</header>
								<ul class="divided">
									<li>
										<article class="tweet">
											Amet nullam fringilla nibh nulla convallis tique ante sociis accumsan.
											<span class="timestamp">5 minutes ago</span>
										</article>
									</li>
									<li>
										<article class="tweet">
											Hendrerit rutrum quisque.
											<span class="timestamp">30 minutes ago</span>
										</article>
									</li>
									<li>
										<article class="tweet">
											Curabitur donec nulla massa laoreet nibh. Lorem praesent montes.
											<span class="timestamp">3 hours ago</span>
										</article>
									</li>
									<li>
										<article class="tweet">
											Lacus natoque cras rhoncus curae dignissim ultricies. Convallis orci aliquet.
											<span class="timestamp">5 hours ago</span>
										</article>
									</li>
								</ul>
							</section>

						<!-- Posts --
							<section class="4u">
								<header>
									<h2 class="fa fa-file circled solo"><span>Posts</span></h2>
								</header>
								<ul class="divided">
									<li>
										<article class="post stub">
											<header>
												<h3><a href="#">Nisl fermentum integer</a></h3>
											</header>
											<span class="timestamp">3 hours ago</span>
										</article>
									</li>
									<li>
										<article class="post stub">
											<header>
												<h3><a href="#">Phasellus portitor lorem</a></h3>
											</header>
											<span class="timestamp">6 hours ago</span>
										</article>
									</li>
									<li>
										<article class="post stub">
											<header>
												<h3><a href="#">Magna tempus consequat</a></h3>
											</header>
											<span class="timestamp">Yesterday</span>
										</article>
									</li>
									<li>
										<article class="post stub">
											<header>
												<h3><a href="#">Feugiat lorem ipsum</a></h3>
											</header>
											<span class="timestamp">2 days ago</span>
										</article>
									</li>
								</ul>
							</section>

						<!-- Photos --
							<section class="4u">
								<header>
									<h2 class="fa fa-camera circled solo"><span>Photos</span></h2>
								</header>
								<div class="row quarter no-collapse">
									<div class="6u">
										<a href="http://mdomaradzki.deviantart.com/art/Air-Lounge-385212062" class="image full"><img src="/design/omt/images/pic10.jpg" alt="" /></a>
									</div>
									<div class="6u">
										<a href="http://mdomaradzki.deviantart.com/art/Paris-City-Streets-II-382623606" class="image full"><img src="/design/omt/images/pic11.jpg" alt="" /></a>
									</div>
								</div>
								<div class="row quarter no-collapse">
									<div class="6u">
										<a href="http://mdomaradzki.deviantart.com/art/Trainride-Visions-383309985" class="image full"><img src="/design/omt/images/pic12.jpg" alt="" /></a>
									</div>
									<div class="6u">
										<a href="http://mdomaradzki.deviantart.com/art/Paris-Metro-382623851" class="image full"><img src="/design/omt/images/pic13.jpg" alt="" /></a>
									</div>
								</div>
								<div class="row quarter no-collapse">
									<div class="6u">
										<a href="http://mdomaradzki.deviantart.com/art/Cliffs-of-Coogee-II-366961860" class="image full"><img src="/design/omt/images/pic14.jpg" alt="" /></a>
									</div>
									<div class="6u">
										<a href="http://mdomaradzki.deviantart.com/art/Stormy-Coast-VII-366561367" class="image full"><img src="/design/omt/images/pic15.jpg" alt="" /></a>
									</div>
								</div>
							</section>
					</div>
					<hr />
                    <!-- end of later -->
					<div class="row">
						<div class="12u">
							
							<!-- Contact -->
								<section class="contact">
									<header>
										<h3>Ønsker du at følge med i hvad vi laver?</h3>
									</header>
									<p>I Odense Muay Thai kan du følge med i hvad der foregår på vores facebook side der er åben for alle.</p>
									<ul class="icons">
										<li><a href="http://www.facebook.com/pages/Odense-Muay-Thai/193561900760138" class="fa fa-facebook solo"><span>Facebook</span></a></li>
									</ul>
								</section>
							
							<!-- Copyright -->
								<div class="copyright">
									<ul class="menu">
										<li>&copy; Odense Muay Thai. All rights reserved.</li>
										<li>Crafted &amp; Licensed by <a href="http://Ryuu.technology/">Ryuu Technology</a></li>
									</ul>
								</div>
							
						</div>
					
					</div>
				</div>
			</div>

	</body>
</html>